### ISSUE TITLE
Prove Injectivity of nat to string conversion functions

### ISSUE THREAD

**Issue by llee454** [sifive/Kami#121]

**Comment by vmurali** [comment]
Didn't @sifive-emarzion prove this?

**Comment by llee454** [comment]
I just Slacked him and discovered that he wrote a proof for natToHex. I didn't notice his commit in StdLibKami. Well, if anyone cares, this proof proves injectivity for all radices and covers the nat_binary_string and nat_decimal_string functions as well as nat_hex_string.

**Comment by vmurali** [comment]
Ok sounds good.

Can we not have natToHex and nat_hex_string?

**Comment by vmurali** [comment]
As in, can you replace natToHex with this function, assuming they have the
same signature and semantics?
