### ISSUE TITLE
Merging master into NewWordLibrary branch

### ISSUE THREAD

**Issue by vmurali** [sifive/Kami#15]
@swarnpriya Please merge master with NewWordLibrary branch (not the other way around). There are a lot of changes that have been made on Syntax.v and other files that shouldn't be lost with your merge. In fact, I would recommend manually merging your changes on a new branch forked from master rather than relying on Git to do the merge properly

**Comment by swarnpriya** [comment]
ok will do that. Was fixing Fpu Properties but will do this first.
