### ISSUE TITLE
@LessThan 4 15 8 = true

### ISSUE THREAD

**Issue by andres-erbsen-sifive** [sifive/Kami#16]
`Register @^"rx_fifo_len" : Bit 4 <- @natToWord 4 15`
conditional `#rx_fifo_len < $$@natToWord 4 8`
state `(@^ ("rx_fifo_len"),  existT (fullType type) (SyntaxKind (Bit 4)) ($15)%word)`
...and I get a goal for the case where the branch is taken.

I am probably missing something obvious here, but :confused:

**Comment by whonore** [comment]
Can you prove that there is a contradiction in the case where the branch is taken?

**Comment by andres-erbsen-sifive** [comment]
..and it indeed was dumb -- I had forgotten to update the `x <- Read "x"` boilerplate.
