### ISSUE TITLE
proof examples?

### ISSUE THREAD

**Issue by andres-erbsen** [sifive/Kami#7]
Hi,

I was trying to figure out how I would use this kami to prove trace inclusion between two modules, and this repository does not seem to contain a good starting point. I presume that the definitions and theorems here were developed while iterating on more or less small examples. Is there any chance these could be added to this repository so we can have an easier time getting started? Or are there example proofs of trace inclusion somewhere online already that I missed?

Thanks,
Andres

**Comment by vmurali** [comment]
You haven't missed anything. Those are present in some of our private
repositories that we haven't made public. I will pull in a FIFO proof from
that and post it right away.

**Comment by vmurali** [comment]
Try this: https://github.com/sifive/TutorialKami, after pulling another
tactic that I wrote. By the way, all the tactics are in Properties.v, and
this tutorial example is instructive for code that doesn't contain methods.
If you have methods, then we need to inline, remove, etc - talk to me about
how to structure code in Kami in the first place.

**Comment by vmurali** [comment]
Closed with Tactics.v file, containing necessary tactics and example.
